### ISSUE TITLE
Chordsify failure

### ISSUE THREAD

**Issue by chrisjbaik** [chrisjbaik/psalted#28]
http://psalted.com/groups/nofilter/if-i-have-u

If I try to make a setlist with the "Chords" layout setting, it breaks :cry:

**Comment by varoot** [comment]
What are the songs in that setlist?


--
Varoot Phasuthadol
http://varoot.com/
M.S. in Information (Human–computer Interaction), University of Michigan
2012

**Comment by varoot** [comment]
Oh I can see the setlist. Am I supposed to be able to see setlists in your
group?


--
Varoot Phasuthadol
http://varoot.com/
M.S. in Information (Human–computer Interaction), University of Michigan
2012

**Comment by chrisjbaik** [comment]
@varoot I don't know if we put any permissions on it.. lol. tbh i'm not too worried because it's not like the list of worship songs you sang carries any private information or anything

**Comment by chrisjbaik** [comment]
@varoot do you know what the issue might be? I'm a little baffled.

**Comment by varoot** [comment]
Hey... I think it's not because of that particular song, but the whole
chord sheet is broken. See if what I committed fixes it.

Anyway, did you move the server or something? Can't seem to find it.

**Comment by chrisjbaik** [comment]
Hmm. No, didn't work still.

Whatcha mean move the server? Haven't touched anything. IP/credentials should still be the same.

**Comment by varoot** [comment]
I just updated Composer and I think it worked now. Let me know if it still
doesn't work for you.

**Comment by chrisjbaik** [comment]
Nice! Thanks.
