### ISSUE TITLE
Theme View Page

### ISSUE THREAD

**Issue by chrisjbaik** [chrisjbaik/psalted#30]
* Need to be able to organize and view songs by themes

**Comment by chengsta** [comment]
How should I let the user access this page?  Extra option on the left sidebar?

**Comment by varoot** [comment]
If you want to give people access, I'd suggest either on left sidebar after Browse Songs, or add it as another "Sort By" on the browse page itself, although it might not be compatible with what's already on the page.

**Comment by chengsta** [comment]
Added a button on the left sidebar

**Comment by chrisjbaik** [comment]
@chengsta awesome! This is really sweet! I pushed it to the live site.

By the way, have you used pull requests in your workflow before? I've found it to be a good way to keep track of features and also to communicate with other people/get feedback before releasing something, and it's a great way to manage workflow with potential teammates/projects:

https://guides.github.com/introduction/flow/

**Comment by chengsta** [comment]
Not officially but oops yeah.  Will do in future
